language: go

arch:
    - AMD64
    - ppc64le

# allow internal package imports, necessary for forked repositories
go_import_path: github.com/onsi/ginkgo

go:
    - 1.14

install:
    - 'go install github.com/onsi/ginkgo/ginkgo'
script: 'ginkgo -r'
